import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import Biograph from "@/containers/about/biograph";
import Gallery from "@/containers/about/gallery";
import Landing from "@/containers/about/landing";
import Team from "@/containers/about/team";

export async function generateMetadata() {
  return {
    title: {
      default: "Zad | About",
      template: "%s",
    },
    description: "Generated by create next app",
    icons: {
      apple: "/zad-logo.svg",
      icon: "/zad-logo.svg",
    },
  };
}

// Viewport export remains separate
export const viewport = "width=device-width, initial-scale=1";

export default function About() {
  return (
    <>
      <Navbar />
      <Landing />
      <Gallery />
      <div className="container mt-32">
        <Biograph />
        <Team />
      </div>
      <Footer />
    </>
  );
}
