import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import Biograph from "@/containers/about/biograph";
import Gallery from "@/containers/about/gallery";
import Landing from "@/containers/about/landing";
import Team from "@/containers/about/team";

export const metadata = {
  title: {
    default: "Zad | About", // Default title when `usePageTitle` isn't used
    template: "%s", // Template for dynamic titles, e.g., "Page Title | My App"
  },
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
  icons: {
    apple: "/zad-logo.svg",
    icon: "/zad-logo.svg",
  },
};

export default function About() {
  return (
    <>
      <Navbar />
      {/* Landing Image */}
      <Landing />

      {/* Pictures from the place and promo video */}
      <Gallery />

      <div className="container mt-32">
        {/* Biograph, mission & Vision  */}
        <Biograph />

        {/* Zad team: “Photos, names, profession”. */}
        <Team />
      </div>

      <Footer />
    </>
  );
}
