import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import Features from "@/containers/home/features";
import Hero from "@/containers/home/hero";
import ImageText from "@/containers/home/imageText";
import Landing from "@/containers/home/landing";
import LeasingPlans from "@/containers/home/leasingPlans";

export const metadata = {
  title: {
    default: "Zad | Home", // Default title when `usePageTitle` isn't used
    template: "%s", // Template for dynamic titles, e.g., "Page Title | My App"
  },
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
  icons: {
    apple: "/zad-logo.svg",
    icon: "/zad-logo.svg",
  },
};

export default function Home() {
  return (
    <>
      <Navbar />
      <Landing />
      <div className="container mx-auto">
        <ImageText />
        <Features />
      </div>
      <LeasingPlans />
      <div className="container">
        <Hero />
      </div>
      <Footer />
    </>
  );
}
