import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import Features from "@/containers/home/features";
import Hero from "@/containers/home/hero";
import ImageText from "@/containers/home/imageText";
import Landing from "@/containers/home/landing";
import LeasingPlans from "@/containers/home/leasingPlans";

export async function generateMetadata() {
  return {
    title: {
      default: "Zad",
      template: "%s",
    },
    description: "Generated by create next app",
    icons: {
      apple: "/zad-logo.svg",
      icon: "/zad-logo.svg",
    },
  };
}

// Viewport export remains separate
export const viewport = "width=device-width, initial-scale=1";

export default function Home() {
  return (
    <>
      <Navbar />
      <Landing />
      <div className="container mx-auto">
        <ImageText />
        <Features />
      </div>
      <LeasingPlans />
      <div className="container">
        <Hero />
      </div>
      <Footer />
    </>
  );
}
