import Layout from "@/layout/layout";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import { El_Messiri, Noto_Kufi_Arabic } from "next/font/google";
import Head from "next/head";

const el_messiry = El_Messiri({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-primary",
});

const noto_kufi = Noto_Kufi_Arabic({
  subsets: ["latin"],
  variable: "--font-secondary",
  weight: "500",
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <main className={`${el_messiry.variable} ${noto_kufi.variable}`}>
      <Head>
        <title>Zad</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/icon.png" />
      </Head>

      <Layout>
        <Component {...pageProps} />
      </Layout>
    </main>
  );
}
