import usePageTitle from "@/hooks/usePageTitle";
import Layout from "@/layout/layout";
import "@/styles/globals.css";
import type { AppProps } from "next/app";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
  const path = usePageTitle();

  return (
    <main>
      <Head>
        <title>Zad | {path}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/zad-logo.svg"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="512×512"
          href="/zad-logo.svg"
        />
      </Head>

      <Layout>
        <Component {...pageProps} />
      </Layout>
    </main>
  );
}
